from sqlalchemy import Column, Integer, String, Date, DateTime
from datetime import datetime
from core.database import Base

class Driver(Base):
    __tablename__ = "drivers"

    id = Column(Integer, primary_key=True, index=True)
    driver_code = Column(String, unique=True, index=True)
    first_name = Column(String, index=True)
    last_name = Column(String, index=True)
    father_name = Column(String)
    gender = Column(String)
    national_id = Column(String, unique=True, index=True)
    id_number = Column(String)
    id_serial = Column(String)
    birth_date = Column(Date)
    issue_date = Column(Date)
    birth_place = Column(String)
    birth_place_type = Column(String)
    birth_place_code = Column(String)
    issue_place = Column(String)
    issue_place_type = Column(String)
    issue_place_code = Column(String)
    nationality = Column(String)
    citizenship = Column(String)
    religion = Column(String)
    sect = Column(String)
    email = Column(String, unique=True, index=True)
    mobile_phone = Column(String)
    license_number = Column(String, unique=True, index=True)
    license_issue_date = Column(Date)
    license_expiry_date = Column(Date)
    vehicle_plate = Column(String)
    experience_years = Column(Integer)
    address_type = Column(String)
    address_title = Column(String)
    city = Column(String)
    city_type = Column(String)
    city_code = Column(String)
    address = Column(String)
    phone = Column(String)
    postal_code = Column(String)
    fax = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
