"""update employee model

Revision ID: 317c2b9f6e31
Revises: f7f683f249e4
Create Date: 2025-07-28 18:09:32.198344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317c2b9f6e31'
down_revision: Union[str, None] = 'f7f683f249e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('personnel_code', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('father_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('national_id', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('id_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('id_serial', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('death_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('issue_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('birth_place', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('birth_place_type', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('birth_place_code', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('issue_place', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('issue_place_type', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('issue_place_code', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('nationality', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('citizenship', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('religion', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('sect', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('mobile_phone', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('work_id_code', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('employee_code', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('effective_employee_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('marital_status', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('effective_marital_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('military_status', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('exemption_type', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('service_area', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('service_branch', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('service_start_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('service_end_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('service_duration', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('education_level_during_service', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('address_type', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('address_title', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('city', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('city_type', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('city_code', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('address', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('fax', sa.String(), nullable=True))
    op.drop_index('ix_employees_name', table_name='employees')
    op.create_index(op.f('ix_employees_national_id'), 'employees', ['national_id'], unique=True)
    op.create_index(op.f('ix_employees_personnel_code'), 'employees', ['personnel_code'], unique=True)
    op.drop_column('employees', 'role')
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_employees_personnel_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_national_id'), table_name='employees')
    op.create_index('ix_employees_name', 'employees', ['name'], unique=False)
    op.drop_column('employees', 'fax')
    op.drop_column('employees', 'postal_code')
    op.drop_column('employees', 'address')
    op.drop_column('employees', 'city_code')
    op.drop_column('employees', 'city_type')
    op.drop_column('employees', 'city')
    op.drop_column('employees', 'address_title')
    op.drop_column('employees', 'address_type')
    op.drop_column('employees', 'education_level_during_service')
    op.drop_column('employees', 'service_duration')
    op.drop_column('employees', 'service_end_date')
    op.drop_column('employees', 'service_start_date')
    op.drop_column('employees', 'service_branch')
    op.drop_column('employees', 'service_area')
    op.drop_column('employees', 'exemption_type')
    op.drop_column('employees', 'military_status')
    op.drop_column('employees', 'effective_marital_date')
    op.drop_column('employees', 'marital_status')
    op.drop_column('employees', 'effective_employee_date')
    op.drop_column('employees', 'employee_code')
    op.drop_column('employees', 'work_id_code')
    op.drop_column('employees', 'mobile_phone')
    op.drop_column('employees', 'sect')
    op.drop_column('employees', 'religion')
    op.drop_column('employees', 'citizenship')
    op.drop_column('employees', 'nationality')
    op.drop_column('employees', 'issue_place_code')
    op.drop_column('employees', 'issue_place_type')
    op.drop_column('employees', 'issue_place')
    op.drop_column('employees', 'birth_place_code')
    op.drop_column('employees', 'birth_place_type')
    op.drop_column('employees', 'birth_place')
    op.drop_column('employees', 'issue_date')
    op.drop_column('employees', 'death_date')
    op.drop_column('employees', 'birth_date')
    op.drop_column('employees', 'id_serial')
    op.drop_column('employees', 'id_number')
    op.drop_column('employees', 'national_id')
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'father_name')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    op.drop_column('employees', 'personnel_code')
    # ### end Alembic commands ###
