from sqlalchemy import Column, Integer, String, Date, DateTime
from datetime import datetime
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class Employee(Base):
    __tablename__ = "employees"

    id = Column(Integer, primary_key=True, index=True)
    personnel_code = Column(String, unique=True, index=True)
    first_name = Column(String, index=True)
    last_name = Column(String, index=True)
    father_name = Column(String)
    gender = Column(String)
    national_id = Column(String, unique=True, index=True)
    id_number = Column(String)
    id_serial = Column(String)
    birth_date = Column(Date)
    death_date = Column(Date, nullable=True)
    issue_date = Column(Date)
    birth_place = Column(String)
    birth_place_type = Column(String)
    birth_place_code = Column(String)
    issue_place = Column(String)
    issue_place_type = Column(String)
    issue_place_code = Column(String)
    nationality = Column(String)
    citizenship = Column(String)
    religion = Column(String)
    sect = Column(String)
    email = Column(String, unique=True, index=True)
    mobile_phone = Column(String)
    work_id_code = Column(String)
    employee_code = Column(String)
    effective_employee_date = Column(Date, nullable=True)
    marital_status = Column(String)
    effective_marital_date = Column(Date, nullable=True)
    military_status = Column(String)
    exemption_type = Column(String)
    service_area = Column(String)
    service_branch = Column(String)
    service_start_date = Column(Date, nullable=True)
    service_end_date = Column(Date, nullable=True)
    service_duration = Column(String)
    education_level_during_service = Column(String)
    address_type = Column(String)
    address_title = Column(String)
    city = Column(String)
    city_type = Column(String)
    city_code = Column(String)
    address = Column(String)
    phone = Column(String)
    postal_code = Column(String)
    fax = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
