services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sarir_user
      POSTGRES_PASSWORD: sarir_pass
      POSTGRES_DB: sarir_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: